apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out .k8s/
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: db-migrate
  name: db-migrate
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-migrate
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out .k8s/
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/k8s-poc-default: "true"
        io.kompose.service: db-migrate
    spec:
      containers:
        - args:
            - /bin/bash
            - -c
            - "while ! nc -z db 5432; do\n  echo \"waiting for PostgreSQL to become available ...\"   \n  sleep 1\ndone\n\ncd alembic\nalembic upgrade head\n"
          env:
            - name: DATABASE_URI
              value: postgresql+psycopg2://mat_admin:passwd@db/mat
          image: kingak/db-migrate-k8s-poc
          imagePullPolicy: Never
          name: db-migrate
          resources: {}
      restartPolicy: Always
status: {}
