# This file is used to define the software stack that makes up MAT (Market Analysis Tool)
# It offers a quick and reliable way to quickly set up and configure the require tools.

version: "3"
services:
  #------------------- CORE STUFF -------------------
  ###----------------- STOCKS------------------------
  harvester-stocks:
    image: kingak/harvester-k8s-poc
    build:
      context: .
      dockerfile: .docker/harvester.dockerfile
    restart: always
    depends_on:
      - kafka
    environment:
      ALPHAVANTAGE_API_KEY: ${ALPHAVANTAGE_API_KEY}
      MAT_STOCK_TICKER_LIST: ${MAT_STOCK_TICKER_LIST}
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    command:
      - /bin/bash
      - -c
      - |
        python harvester.py -t ${MAT_STOCK_TICKER_LIST}

  ingestor-stocks:
    image: kingak/ingestor-k8s-poc
    build:
      context: .
      dockerfile: .docker/ingestor.dockerfile
    restart: always
    depends_on:
      - kafka
      - db
    environment:
      DATABASE_URI: "postgresql+psycopg2://mat_admin:passwd@db/mat" # TODO: update URI string to use env vars
      #     DATABASE_URI: "postgresql+psycopg2://${MAT_DATABASE_USER:-mat_admin}:${POSTGRES_PASSWORD:-passwd}@db/${MAT_DATABASE_NAME:-mat}"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    command:
      - /bin/bash
      - -c
      - |
        python ingestor.py -t stock

  ###------------------- PUB/SUB QUEUE -------------------
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.2
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - ALLOW_PLAINTEXT_LISTENER=yes
      - BITNAMI_DEBUG=TRUE
      - KAFKA_ENABLE_KRAFT=no
    depends_on:
      - zookeeper

  ###------------------- DB BACKEND -------------------
  db:
    image: postgres:13.3-buster
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "${MAT_DATABASE_NAME:-mat}"
      POSTGRES_USER: "${MAT_DATABASE_USER:-mat_admin}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-passwd}"

  db-migrate:
    image: kingak/db-migrate-k8s-poc
    build:
      context: .
      dockerfile: .docker/db-migrate.dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URI: "postgresql+psycopg2://mat_admin:passwd@db/mat" # TODO: update URI string to use env vars
      # DATABASE_URI: "postgresql+psycopg2://${POSTGRES_USER:-mat_admin}:${POSTGRES_PASSWORD:-passwd}@${POSTGRES_HOSTNAME:-localhost}/${POSTGRES_DB:-mat}"
    command:
      - /bin/bash
      - -c
      - |
        while ! nc -z db 5432; do
          echo "waiting for PostgreSQL to become available ..."   
          sleep 1
        done

        cd alembic
        alembic upgrade head

volumes:
  postgresql-data:
    driver: local
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
