apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/mango/stuff/bin/kompose -f docker-compose.yml convert -o k8s/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: flink-ingestor-taskmanager
  name: flink-ingestor-taskmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: flink-ingestor-taskmanager
  template:
    metadata:
      annotations:
        kompose.cmd: /home/mango/stuff/bin/kompose -f docker-compose.yml convert -o k8s/
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: flink-ingestor-taskmanager
    spec:
      containers:
        - args:
            - taskmanager
          env:
            - name: FLINK_PROPERTIES
              value: |2
                jobmanager.rpc.address: flink-ingestor-jobmanager
                taskmanager.numberOfTaskSlots: 2
                parallelism.default: 2
          image: kingak/flink-app:latest
          name: flink-ingestor-taskmanager
      restartPolicy: Always
