apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/mango/stuff/bin/kompose -f docker-compose.yml convert -o k8s/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: py-harvester
  name: py-harvester
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: py-harvester
  template:
    metadata:
      annotations:
        kompose.cmd: /home/mango/stuff/bin/kompose -f docker-compose.yml convert -o k8s/
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: py-harvester
    spec:
      containers:
        - args:
            - -k
            - W4SEKZP25WD8OZDT
            - -s
            - VZ,T,F
            - -b
            - kafka:9092
          env:
            - name: ALPHAVANTAGE_API_KEY
              value: W4SEKZP25WD8OZDT
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: MAT_STOCK_TICKER_LIST
              value: VZ,T,F
          image: kingak/py-harvester
          name: py-harvester
      restartPolicy: Always
