apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/mango/stuff/bin/kompose -f docker-compose.yml convert -o k8s/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
  selector:
    io.kompose.service: zookeeper
